apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: agi-team-xia.ma
  description: test creating selfservice by xia ma
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/agi-team
  lifecycle: experimental
